os:
  - linux
services:
  - docker
language: node_js
node_js:
  - "8.9.4"
jdk:
  - oraclejdk8
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
env:
  global:
    - PROFILE=dev
    - RUN_APP=1
    - PROTRACTOR=0
    - JHIPSTER_TRAVIS=$HOME/generator-jhipster/travis
    - JHIPSTER_SAMPLES=$TRAVIS_BUILD_DIR/travis/samples-kotlin
    - JHIPSTER_SCRIPTS=$JHIPSTER_TRAVIS/scripts
    - APP_FOLDER=$HOME/app
    - UAA_APP_FOLDER=$HOME/uaa
    # environment properties
    - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    - SPRING_JPA_SHOW_SQL=false

    # if JHIPSTER_DEPENDENCIES_BRANCH value is release, use the release from Maven
    - JHIPSTER_DEPENDENCIES_REPO=https://github.com/jhipster/jhipster-dependencies.git
    - JHIPSTER_DEPENDENCIES_BRANCH=release
    # if JHIPSTER_LIB_BRANCH value is release, use the release from Maven
    - JHIPSTER_LIB_REPO=https://github.com/jhipster/jhipster.git
    - JHIPSTER_LIB_BRANCH=release
    # if JHIPSTER_BRANCH value is release, use the release from NPM
    - JHIPSTER_REPO=https://github.com/jhipster/generator-jhipster.git
    - JHIPSTER_BRANCH=master

  matrix:
    # - JHIPSTER=ngx-default PROFILE=prod PROTRACTOR=1
    # - JHIPSTER=ngx-psql-es-noi18n PROFILE=prod PROTRACTOR=1
    - JHIPSTER=ngx-gradle-fr PROFILE=prod PROTRACTOR=1
    # - JHIPSTER=ngx-mariadb-oauth2-sass-infinispan PROTRACTOR=1
    # - JHIPSTER=ngx-h2mem-social-ws-nol2
    # - JHIPSTER=ngx-mongodb-kafka-cucumber
    # - JHIPSTER=ngx-session-cassandra-fr
    # - JHIPSTER=ngx-couchbase
    # - JHIPSTER=ms-ngx-gateway-eureka
    # - JHIPSTER=ms-ngx-gateway-consul
    # - JHIPSTER=ms-ngx-gateway-uaa
    # - JHIPSTER=ms-micro-eureka
    # - JHIPSTER=ms-micro-consul
    # - JHIPSTER=react-default

before_install:
  - jdk_switcher use oraclejdk8
  - java -version
  - export TZ=Australia/Canberra
  - date
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
  # Use this for Protractor
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # Install Yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn -v
  - yarn global add yo
  - ls -al $TRAVIS_BUILD_DIR
  - ls -al $TRAVIS_BUILD_DIR/travis/
  - ls -al $TRAVIS_BUILD_DIR/travis/scripts/
install:
  - $TRAVIS_BUILD_DIR/travis/scripts/00-install-jhipster.sh
  # generate project and entities
  # TODO: need to be removed as soon as entities are ready
  # - $JHIPSTER_SCRIPTS/01-generate-entities.sh
  - $TRAVIS_BUILD_DIR/travis/scripts/02-generate-project.sh
script:
  - $JHIPSTER_SCRIPTS/03-docker-compose.sh
  - $JHIPSTER_SCRIPTS/04-tests.sh
  - $JHIPSTER_SCRIPTS/05-run.sh
