name: KHipster Generated Applications CI
on: [push, pull_request]
env:
    JHI_RUN_APP: 1
    JHI_E2E: 0
    JHI_JDK: 11
    JHI_LIB_REPO: https://github.com/jhipster/jhipster-bom.git
    JHI_LIB_BRANCH: release
    JHI_GEN_REPO: https://github.com/jhipster/generator-jhipster.git
    JHI_GEN_BRANCH: v7.0.0-beta.0
    SPRING_OUTPUT_ANSI_ENABLED: ALWAYS
    SPRING_JPA_SHOW_SQL: false
    JHI_DISABLE_WEBPACK_LOGS: true
    JHI_E2E_HEADLESS: true
    JHI_SCRIPTS_PATH: generator-jhipster/test-integration/scripts
    JHI_SCRIPTS: $HOME/$JHI_SCRIPTS_PATH
    KOTLIN_JHI_SCRIPTS: ${{ github.workspace }}/test-integration/scripts
    NG_CLI_ANALYTICS: 'false'
    JHI_GITHUB_CI: true
    FORCE_COLOR: 1
    # https://github.com/actions/virtual-environments/issues/1499#issuecomment-689467080
    MAVEN_OPTS: >-
        -Dhttp.keepAlive=false
        -Dmaven.wagon.http.pool=false
        -Dmaven.wagon.httpconnectionManager.ttlSeconds=120
jobs:
    applications:
        name: ${{ matrix.app-type }} application test suite
        runs-on: ${{ matrix.os }}
        timeout-minutes: 40
        strategy:
            fail-fast: false
            matrix:
                node_version: [12.x]
                os: [ubuntu-20.04]
                app-type: [ngx-session-cassandra-fr, ngx-mongodb-kafka-cucumber]
                include:
                    - app-type: ngx-session-cassandra-fr
                      entity: cassandra
                      profile: dev
                    - app-type: ngx-mongodb-kafka-cucumber
                      entity: mongodb
                      profile: dev
        env:
            JHI_ENTITY: ${{ matrix.entity }}
            JHI_APP: ${{ matrix.app-type }}
            JHI_PROFILE: ${{ matrix.profile }}
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node_version }}
            - uses: actions/setup-java@v1
              with:
                  java-version: '11.x'
            - name: Stop MySQL server
              run: sudo /etc/init.d/mysql stop
            - name: Config git variables
              run: $KOTLIN_JHI_SCRIPTS/04-git-config.sh
            - name: Install KHipster
              run: $KOTLIN_JHI_SCRIPTS/10-install-jhipster-kotlin.sh
            - name: Generate entities
              run: $HOME/$JHI_SCRIPTS_PATH/11-generate-entities.sh
            - name: Generate project
              run: $KOTLIN_JHI_SCRIPTS/12-generate-project-kotlin.sh
            - name: Replace version in the generated project
              run: $HOME/$JHI_SCRIPTS_PATH/13-replace-version-generated-project.sh
            - name: Jhipster Info
              run: $HOME/$JHI_SCRIPTS_PATH/14-jhipster-info.sh
            - name: Start docker containers
              run: $HOME/$JHI_SCRIPTS_PATH/20-docker-compose.sh
            - name: Run backend tests
              run: $HOME/$JHI_SCRIPTS_PATH/21-tests-backend.sh
            - name: Run frontend tests
              run: $HOME/$JHI_SCRIPTS_PATH/22-tests-frontend.sh
            - name: Package application
              run: $HOME/$JHI_SCRIPTS_PATH/23-package.sh
            - name: Run e2e tests
              run: $HOME/$JHI_SCRIPTS_PATH/24-tests-e2e.sh
            - name: Sonar analysis
              run: $HOME/$JHI_SCRIPTS_PATH/25-sonar-analyze.sh
